drugCatcher/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

home/urls.py
from django.urls import path
from .views import index, CreateAppointment, load_companies, confirm

app_name = 'home'

urlpatterns = [
    path('', index, name='index'),
    path('request', CreateAppointment.as_view(template_name='home/createAppointment.html'), name='createAppointment'),
    path('confirm', confirm, name='confirm'),
    
    # AJAX for some ungodly reason
    path('ajax/load-companies', load_companies, name='ajaxLoadComp'),
]

users/urls.py
from django.urls import path

app_name = 'users'

urlpatterns = [

]

home/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

# Django's Moto is : Keep your Models fat and your Views small
# and i did just that

# Create your models here.
class Country(models.Model):
    name = models.CharField(max_length=70)

    def __str__(self):
        return self.name

class Company(models.Model):
    name = models.CharField(max_length=150)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Objective(models.Model):
    Type = models.CharField(max_length=60)

    def __str__(self):
        return self.Type

class Appointment(models.Model):

    firstName = models.CharField(max_length=30)
    lastName = models.CharField(max_length=30)
    email = models.EmailField()
    phoneNumber = PhoneNumberField()
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    company = models.ForeignKey(Company, on_delete=models.SET_NULL, null=True)
    objective = models.ForeignKey(Objective, on_delete=models.SET_NULL, null=True)
    description = models.TextField(max_length='600')
    
    def __str__(self):
        return self.firstName + " " + self.lastName

home/forms.py
from django import forms
from .models import Appointment, Company, Country, Objective

class AppointmentCreationForm(forms.ModelForm):

    class Meta:
        model = Appointment
        fields = ['firstName', 'lastName', 'email', 'phoneNumber', 'country', 'company', 'objective', 'description']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['company'].queryset = Company.objects.none()
        
        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['company'].queryset = Company.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['company'].queryset = self.instance.country.company_set.order_by('name')

home/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView
from .models import Appointment, Company
from .forms import AppointmentCreationForm

# Create your views here.

def index(request):
    return render(request, 'home/index.html')


class CreateAppointment(CreateView):
    model = Appointment
    form_class = AppointmentCreationForm
    success_message = "Appointment was set successfully"
    succes_url = reverse_lazy('home:confirm')

    def get_success_url(self):
        return reverse('home:confirm')
    



def load_companies(request):
    country_id = request.GET.get('country')
    companies = Company.objects.filter(country_id=country_id).order_by('name')
    return render(request, 'home/companyList.html', {'companies': companies})

def confirm(request):
    context = {'title': 'Confirm'}
    return render(request, "home/confirm.html", context)

users/views.py
from django.shortcuts import render

# Create your views here.

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "base/head.html" %}
</head>

<body>

    {% include "base/nav.html" %}

    {% include "base/messages.html" %}

    {% block content %}
    {% endblock content %}


    {% include "base/javascript.html" %}
</body>
</html>

templates/base/head.html
{% load static %}
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

<!--Import Google Icon Font-->
<!-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> -->

<!--Let browser know website is optimized for mobile-->
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

<!--Import materialize.css-->
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> -->


<link rel="shortcut icon" type="image/x-icon" href="{% static 'base/images/icon.ico' %}">


{% if title %}
    <title>DrugCatcher - {{ title }}</title>
{% else %}
    <title>DrugCatcher</title>
{% endif %}

templates/base/javascript.html
<!-- <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

<script>
$(document).ready(function(){

  $('select').formSelect();

});
</script>  -->

templates/base/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="text-center alert alert-{{ message.tags }}">
            {{ message|safe }}
        </div>
    {% endfor %}
{% endif %}

templates/base/nav.html
<nav>
    <div class="nav-wrapper container">
      <a href="{% url 'home:index' %}" class="brand-logo center">Drug Catchers</a>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li><a href="{% url 'home:index' %}">Home</a></li>
      </ul>
    </div>
</nav>

templates/home/companyList.html
<option value="">select country</option>
{% for company in companies %}
<option value="{{ company.pk }}">{{ company.name }}</option>
{% endfor %}

templates/home/confirm.html
{% extends 'base/base.html' %}

{% block content %}

<h2>The appointment is confirmed</h2>

{% endblock content %}

templates/home/createAppointment.html
{% extends 'base/base.html' %}

{% block content %}

<br><br> 

<div class="container">
    <h2 class="center">Create Appointment</h2>
</div>


<div class="container">
    <form method="post" id="appForm" data-companies-url="{% url 'home:ajaxLoadComp' %}" novalidate>
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" value="save">Create</button>
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
$("#id_country").change(function () {
    var url = $("#appForm").attr("data-companies-url");
    var countryId = $(this).val();

    $.ajax({
    url: url,
    data: {
        'country': countryId
    },
    success: function (data) {
        $("#id_company").html(data);
    }
    });

});
</script>


{% endblock content %}

templates/home/index.html
{% extends 'base/base.html' %}

{% block content %}

<!-- ik that breaks are not the best practice in frontend dev, but i needed an appealing display for my backend -->
<br><br> 
<h3 class="container center">Request an appointment with our Team now!</h3>

<br><br>

<div class="center container">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/fMUxzrgZvZQ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
    
<br><br>
<div class="container center">
    <a class="waves-effect waves-light btn" href="{% url 'home:createAppointment' %}">Request Appointment</a>
</div>


{% endblock content %}